version: '3'
services:
 database:
  image: ma_db_img
  container_name: ma_db_cnt
  build: ./micro-app-db
 service:
  image: ma_srv_img
  container_name: ma_srv_cnt
  build: ./micro-app-service
  ports:
   - "8080:8080"
  links:
   - database
  depends_on:
   - database