version: '3'
services:
 database:
  image: database_img
  container_name: database_cnt
  build: ./micro-app-db
 service:
  image: service_img
  container_name: service_cnt
  build: ./micro-app-service
  ports:
   - "8080:8080"
  links:
   - database
  depends_on:
   - database
 view:
  image: view_img
  container_name: view_cnt
  build: ./micro-app-view
  ports:
   - "4200:80"
  links:
   - service
  depends_on:
   - service